# These limits are used by MoveIt and augment/override the definitions in
# ur_description.
# You can confirm parameters are loaded despite warning, by:
# ros2 param get /move_group robot_description_planning.joint_limits.joint_1.max_deceleration
/**/move_group:
  ros__parameters:
    robot_description_planning:
      joint_limits:
        $(var tf_prefix)joint_1:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        $(var tf_prefix)joint_2:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        $(var tf_prefix)joint_3:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        $(var tf_prefix)joint_4:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        $(var tf_prefix)joint_5:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        $(var tf_prefix)joint_6:
          has_acceleration_limits: true
          max_acceleration: 0.5236 # 30 deg/s^2
          has_deceleration_limits: true
          max_deceleration: -0.5236 # 30 deg/s^2
          has_velocity_limits: true
          max_velocity: 1.0472 # 60 deg/s
        $(var tf_prefix)gripper_jaw1_joint:
          has_acceleration_limits: true
          max_acceleration: 0.1 # m/s^2
          has_deceleration_limits: true
          max_deceleration: -0.1 # m/s^2
          has_velocity_limits: true
          max_velocity: 0.05 # m/s

      cartesian_limits:
        max_trans_vel: 0.05 # m/s
        max_trans_acc: 0.01 # m/s^2
        max_trans_dec: -0.01 # m/s^2
        max_rot_vel: 0.08727 # 5 deg/s
